151 Fix client name sorting
happybottoms/coverd pull request #214
Opened 2020-10-04 10:09 UTC by ffeliks

At the moment the API responds with status code 500 due to `fullName` not being an actual column. I updated it to sort by `firstname`. 

Should this be `ORDER BY firstname DESC, lastname DESC` instead? However this would create an if clause to the repository class.

I also noticed issue #30 however at the moment I am not sure how to provide a generic solution for all cases. This PR aims to be a quick fix so that the users will not experience unexpected behavior.

2020-10-04 19:26 UTC, akoebbe commented
I see what you're saying. While just doing first name would get us part way there. I'd be ok setting up a special case in the repository if `$sort` is `c.fullName` around line 61 or `ClientRepository` with the ORDER clause you mentioned.

2020-10-04 19:51 UTC, ffeliks commented
Updated `ClientRepository` to handle `fullName` sorting

2020-10-04 20:29 UTC, akoebbe requested changes
Real small order of operation changes.

2020-10-04 20:29 UTC, akoebbe commented on src/Repository/ClientRepository.php
> -            if (!strstr($sortField, '.')) {
Let's keep this if statement by itself first, since the `fullName` sort could come in with or without a `c.`

2020-10-04 20:29 UTC, akoebbe commented on src/Repository/ClientRepository.php
> +                $qb->orderBy($sortField, $sortDirection);
Let's just keep this line as the body of the `else`.

2020-10-05 17:40 UTC, ffeliks commented on src/Repository/ClientRepository.php
> -            if (!strstr($sortField, '.')) {
Yes makes sense. I've moved this if statement to the top.

2020-10-06 03:02 UTC, akoebbe approved these changes
Perfect! Thank you1

2020-10-06 03:02 UTC, merged